### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'typeName') when setting queryParams

### ISSUE THREAD

**Issue by GorgeousPuree** [omermecitoglu/next-openapi-route-handler#12]
```
import { PaginationRequestDTO } from '@/models/entities/order';

export const { GET } = defineRoute({
  operationId: 'getOrders',
  method: 'GET',
  summary: 'Get orders',
  description: 'Get an existing order',
  tags: ['Orders'],
  queryParams: PaginationRequestDTO,
  action: async () => {
    const orders = await getOrders(queryParams);
    return Response.json(orders);
  },
  responses: {
    200: {
      description: 'Order details retrieved successfully',
      content: GetOrdersResponse,
    },
    400: { description: 'Unknown sort column names' },
  },
});
```
```
export const PaginationRequestDTO = z.object({
  pageNumber: z.number(),
  numberOfEntitiesPerPage: z.number(),
});
```

This code throws:

```
Collecting page data  ..An error occured while evaluating the route exports from "C:\Users\Petya\WebstormProjects\aaa\src\app\api\orders\route.ts"
TypeError: Cannot read properties of undefined (reading 'typeName')
    at parseDef (C:\Users\Petya\WebstormProjects\aaa\node_modules\zod-to-json-schema\dist\cjs\parseDef.js:52:46)
    at zodToJsonSchema (C:\Users\Petya\WebstormProjects\aaa\node_modules\zod-to-json-schema\dist\cjs\zodToJsonSchema.js:22:45)
    at convertToOpenAPI (C:\Users\Petya\WebstormProjects\aaa\node_modules\@omer-x\next-openapi-route-handler\dist\index.cjs:67:64)
    at resolveParams (C:\Users\Petya\WebstormProjects\aaa\node_modules\@omer-x\next-openapi-route-handler\dist\index.cjs:194:18)
    at defineRoute (C:\Users\Petya\WebstormProjects\aaa\node_modules\@omer-x\next-openapi-route-handler\dist\index.cjs:301:8)
    at eval (eval at safeEval (C:\Users\Petya\WebstormProjects\aaa\.next\server\chunks\764.js:425:16), <anonymous>:73:56)
    at safeEval (C:\Users\Petya\WebstormProjects\aaa\.next\server\chunks\764.js:425:16)
    at getRouteExports (C:\Users\Petya\WebstormProjects\aaa\.next\server\chunks\764.js:437:20)
    at async generateOpenApiSpec (C:\Users\Petya\WebstormProjects\aaa\.next\server\chunks\764.js:644:39)
    at async C:\Users\Petya\WebstormProjects\aaa\.next\server\app\api\swagger\route.js:188:21

> Build error occurred
Error: Failed to collect page data for /api/swagger
    at C:\Users\Petya\WebstormProjects\aaa\node_modules\next\dist\build\utils.js:1258:15 {
  type: 'Error'
}
```
But if instead of using `PaginationRequestDTO`, I'll define `queryParams` inline:

```
queryParams: z.object({
  pageNumber: z.number(),
  numberOfEntitiesPerPage: z.number(),
})
```
it works fine. I'm using the same zod object definition, the difference is whether I use predefined DTO for it or define it inline. What could be the problem?

**Comment by omermecitoglu** [comment]
Did you add `PaginationRequestDTO` to your schema collection like in [here](https://github.com/omermecitoglu/example-user-service/blob/e5f19cee241eb39ca6b74e5e797c2494ed54d5ee/src/app/swagger/route.ts#L6) and [here](https://github.com/omermecitoglu/example-user-service/blob/e5f19cee241eb39ca6b74e5e797c2494ed54d5ee/src/app/page.tsx#L7)?

**Comment by GorgeousPuree** [comment]
> Did you add `PaginationRequestDTO` to your schema collection like in [here](https://github.com/omermecitoglu/example-user-service/blob/e5f19cee241eb39ca6b74e5e797c2494ed54d5ee/src/app/swagger/route.ts#L6) and [here](https://github.com/omermecitoglu/example-user-service/blob/e5f19cee241eb39ca6b74e5e797c2494ed54d5ee/src/app/page.tsx#L7)?

Yes. If I don't add it, it gives another error: `ReferenceError: GetOrdersRequestDTO is not defined`, which is expected.

This issue occurs only with queryParams.

**Comment by omermecitoglu** [comment]
Can you provide a minimal reproducible example?
